version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: moodle_postgres
    restart: always
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodlepassword
      POSTGRES_DB: moodledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    restart: always
    depends_on:
      - postgres
    environment:
      MOODLE_DATABASE_TYPE: pgsql
      MOODLE_DATABASE_HOST: postgres
      MOODLE_DATABASE_PORT_NUMBER: 5432
      MOODLE_DATABASE_USER: moodle
      MOODLE_DATABASE_PASSWORD: moodlepassword
      MOODLE_DATABASE_NAME: moodledb
    ports:
      - "8080:8080"
   
