version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: moodle_postgres
    restart: always
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: moodlepassword
      POSTGRES_DB: moodledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
